services:

  postgres:
    image: postgres:18
    container_name: postgres-internals-research
    restart: unless-stopped

    environment:
      POSTGRES_USER: research
      POSTGRES_PASSWORD: research
      POSTGRES_DB: research

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres-research.conf:/etc/postgresql/postgresql.conf:ro

    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U research -d research"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

